theme: jekyll-theme-minimal
title: ğŸ§”ğŸ»ğŸ’»ğŸ¥¼ğŸ”¬âœ’ï¸ğŸ“„
description: Nimesh Chahare's CV
[Work Email](mailto:nchahare@ibecbarcelona.eu) / [Gmail](mailto:chaharenimesh@gmail.com) /[LinkedIn](https://www.linkedin.com/in/nchahare/) / [GitHub](https://github.com/nchahare/) / [Twitter](https://twitter.com/onenimesa/)
